### ISSUE TITLE
hs.crash.crashLog Question

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1664]
@cmsj - When using `hs.crash.crashLog("This is a test")` - where do you actually find this breadcrumb in Fabric? Any ideas?

**Comment by cmsj** [comment]
Annoyingly, no. I need to figure out why, because it’s made 0.9.59 a waste of time. There’s too much indirection on the logging - I’ll try to get this sorted ASAP

**Comment by cmsj** [comment]
Should be fixed by a2c5182

**Comment by latenitefilms** [comment]
@cmsj - I'm still not sure where you actually find this information in Fabric? I can't see anything in the crash log?

```
# Application: CommandPost
# Version: 1.0.0-beta.22
# Bundle Identifier: org.latenitefilms.CommandPost
# Issue #: 76
# Issue ID: 5a6f20cc8cb3c2fa63d92f1f
# Session ID: 13131e016b554b12b29feec79778e8a7_DNE_0_v2
# Date: 2018-01-31T11:09:00Z
# OS Version: 10.13.2 (17C88)
# Device: MacBook Pro 14,3
# RAM Free: 25.5%
# Disk Free: 5.3%

#0. Crashed: com.apple.main-thread
0  CommandPost                    0x1069cad39 -[Crashlytics crash] + 4
1  internal.so                    0x10cad815c burnTheWorld (internal.m:39)
2  LuaSkin                        0x106c70920 luaD_precall (ldo.c:454)
3  LuaSkin                        0x106c6d2ce luaV_execute (lvm.c:1149)
4  LuaSkin                        0x106c70a76 luaD_call (ldo.c:517)
5  LuaSkin                        0x106c70ab7 luaD_callnoyield (ldo.c:527)
6  LuaSkin                        0x106c786bb luai_objcttry (lobjectivec_exceptions.m:173)
7  LuaSkin                        0x106c70f85 luaD_pcall (ldo.c:162)
8  LuaSkin                        0x106c81588 lua_pcallk (lapi.c:968)
9  LuaSkin                        0x106c7e0ea luaB_xpcall (lbaselib.c:442)
10 LuaSkin                        0x106c70920 luaD_precall (ldo.c:454)
11 LuaSkin                        0x106c6ee45 luaV_execute (lvm.c:1134)
12 LuaSkin                        0x106c70a76 luaD_call (ldo.c:517)
13 LuaSkin                        0x106c70ab7 luaD_callnoyield (ldo.c:527)
14 LuaSkin                        0x106c786bb luai_objcttry (lobjectivec_exceptions.m:173)
15 LuaSkin                        0x106c70f85 luaD_pcall (ldo.c:162)
16 LuaSkin                        0x106c81588 lua_pcallk (lapi.c:968)
17 LuaSkin                        0x106c65713 -[LuaSkin protectedCallAndTraceback:nresults:] (Skin.m:227)
18 CommandPost                    0x1069277cc MJLuaRunString (MJLua.m:737)
19 CommandPost                    0x106925904 -[MJConsoleWindowController tryMessage:] (MJConsoleWindowController.m:152)
20 AppKit                         0x7fff319d675a -[NSApplication(NSResponder) sendAction:to:from:] + 312
21 AppKit                         0x7fff3147c933 -[NSControl sendAction:to:] + 86
22 AppKit                         0x7fff313ee1a6 -[NSTextField textDidEndEditing:] + 937
23 CommandPost                    0x10692643c -[HSGrowingTextField textDidEndEditing:] (HSGrowingTextField.m:20)
24 CoreFoundation                 0x7fff33c71a3c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
25 CoreFoundation                 0x7fff33c7192a _CFXRegistrationPost + 442
26 CoreFoundation                 0x7fff33c71672 ___CFXNotificationPost_block_invoke + 50
27 CoreFoundation                 0x7fff33c2f450 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1664
28 CoreFoundation                 0x7fff33c2e583 _CFXNotificationPost + 595
29 Foundation                     0x7fff35d213c7 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
30 AppKit                         0x7fff3156277a -[NSTextView(NSPrivate) _giveUpFirstResponder:] + 440
31 AppKit                         0x7fff313db0ff -[NSTextView doCommandBySelector:] + 200
32 AppKit                         0x7fff313db013 -[NSTextInputContext(NSInputContext_WithCompletion) doCommandBySelector:completionHandler:] + 118
33 AppKit                         0x7fff313bc55a -[NSKeyBindingManager(NSKeyBindingManager_MultiClients) interpretEventAsCommand:forClient:] + 2898
34 AppKit                         0x7fff31c55523 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke.1109 + 360
35 AppKit                         0x7fff31c55352 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke_3 + 79
36 AppKit                         0x7fff313c3d95 -[NSTextInputContext tryHandleEvent_HasMarkedText_withDispatchCondition:dispatchWork:continuation:] + 92
37 AppKit                         0x7fff31c552d1 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke.1099 + 251
38 HIToolbox                      0x7fff32fa3b7e __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_5 + 70
39 HIToolbox                      0x7fff32fa2a36 ___ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec_block_invoke + 110
40 AppKit                         0x7fff31c4dd30 __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke.320 + 580
41 AppKit                         0x7fff313bd8eb __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke_2 + 79
42 AppKit                         0x7fff313bd86e -[NSTextInputContext tryHandleTSMEvent_HasMarkedText_withDispatchCondition:dispatchWork:continuation:] + 92
43 AppKit                         0x7fff313bd3d1 -[NSTextInputContext handleTSMEvent:completionHandler:] + 1722
44 AppKit                         0x7fff313bcca1 _NSTSMEventHandler + 311
45 HIToolbox                      0x7fff32f4c814 DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1541
46 HIToolbox                      0x7fff32f4bb5d SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 374
47 HIToolbox                      0x7fff32f4b9d3 SendEventToEventTargetWithOptions + 45
48 HIToolbox                      0x7fff32f9fc89 SendTSMEvent_WithCompletionHandler + 389
49 HIToolbox                      0x7fff32fa0154 __SendUnicodeTextAEToUnicodeDoc_WithCompletionHandler_block_invoke + 403
50 HIToolbox                      0x7fff32f9ffb2 __SendFilterTextEvent_WithCompletionHandler_block_invoke + 219
51 HIToolbox                      0x7fff32f9fcd8 SendTSMEvent_WithCompletionHandler + 468
52 HIToolbox                      0x7fff32f9fad7 SendFilterTextEvent_WithCompletionHandler + 233
53 HIToolbox                      0x7fff32f9f796 SendUnicodeTextAEToUnicodeDoc_WithCompletionHandler + 290
54 HIToolbox                      0x7fff32f9f54a __utDeliverTSMEvent_WithCompletionHandler_block_invoke_2 + 289
55 HIToolbox                      0x7fff32f9f3cb __utDeliverTSMEvent_WithCompletionHandler_block_invoke + 405
56 HIToolbox                      0x7fff32f9f1b8 TSMKeyEvent_WithCompletionHandler + 636
57 HIToolbox                      0x7fff32f9eefc __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_4 + 262
58 HIToolbox                      0x7fff32f9ed17 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_3 + 263
59 HIToolbox                      0x7fff32f9ea52 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_2 + 288
60 HIToolbox                      0x7fff32f9e7a8 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke + 280
61 HIToolbox                      0x7fff32f9dd9f TSMProcessRawKeyEventWithOptionsAndCompletionHandler + 3433
62 AppKit                         0x7fff31c5514d __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke.1090 + 115
63 AppKit                         0x7fff31c5451b __204-[NSTextInputContext tryTSMProcessRawKeyEvent_orSubstitution:dispatchCondition:setupForDispatch:furtherCondition:doubleSpaceSubstitutionCondition:doubleSpaceSubstitutionWork:dispatchTSMWork:continuation:]_block_invoke.1016 + 120
64 AppKit                         0x7fff31c54384 -[NSTextInputContext tryTSMProcessRawKeyEvent_orSubstitution:dispatchCondition:setupForDispatch:furtherCondition:doubleSpaceSubstitutionCondition:doubleSpaceSubstitutionWork:dispatchTSMWork:continuation:] + 255
65 AppKit                         0x7fff31c54b91 -[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:] + 1237
66 AppKit                         0x7fff31c54211 -[NSTextInputContext _handleEvent:allowingSyntheticEvent:] + 114
67 AppKit                         0x7fff313bb74a -[NSView interpretKeyEvents:] + 209
68 AppKit                         0x7fff313bb56e -[NSTextView keyDown:] + 724
69 AppKit                         0x7fff31b73029 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 5040
70 AppKit                         0x7fff31b7185c -[NSWindow(NSEventRouting) sendEvent:] + 497
71 AppKit                         0x7fff319d2fa3 -[NSApplication(NSEvent) sendEvent:] + 2751
72 AppKit                         0x7fff31233d9d -[NSApplication run] + 812
73 AppKit                         0x7fff31202f1a NSApplicationMain + 804
74 libdyld.dylib                  0x7fff5b4b0115 start + 1

--

#0. Crashed: com.apple.main-thread
0  CommandPost                    0x1069cad39 -[Crashlytics crash] + 4
1  internal.so                    0x10cad815c burnTheWorld (internal.m:39)
2  LuaSkin                        0x106c70920 luaD_precall (ldo.c:454)
3  LuaSkin                        0x106c6d2ce luaV_execute (lvm.c:1149)
4  LuaSkin                        0x106c70a76 luaD_call (ldo.c:517)
5  LuaSkin                        0x106c70ab7 luaD_callnoyield (ldo.c:527)
6  LuaSkin                        0x106c786bb luai_objcttry (lobjectivec_exceptions.m:173)
7  LuaSkin                        0x106c70f85 luaD_pcall (ldo.c:162)
8  LuaSkin                        0x106c81588 lua_pcallk (lapi.c:968)
9  LuaSkin                        0x106c7e0ea luaB_xpcall (lbaselib.c:442)
10 LuaSkin                        0x106c70920 luaD_precall (ldo.c:454)
11 LuaSkin                        0x106c6ee45 luaV_execute (lvm.c:1134)
12 LuaSkin                        0x106c70a76 luaD_call (ldo.c:517)
13 LuaSkin                        0x106c70ab7 luaD_callnoyield (ldo.c:527)
14 LuaSkin                        0x106c786bb luai_objcttry (lobjectivec_exceptions.m:173)
15 LuaSkin                        0x106c70f85 luaD_pcall (ldo.c:162)
16 LuaSkin                        0x106c81588 lua_pcallk (lapi.c:968)
17 LuaSkin                        0x106c65713 -[LuaSkin protectedCallAndTraceback:nresults:] (Skin.m:227)
18 CommandPost                    0x1069277cc MJLuaRunString (MJLua.m:737)
19 CommandPost                    0x106925904 -[MJConsoleWindowController tryMessage:] (MJConsoleWindowController.m:152)
20 AppKit                         0x7fff319d675a -[NSApplication(NSResponder) sendAction:to:from:] + 312
21 AppKit                         0x7fff3147c933 -[NSControl sendAction:to:] + 86
22 AppKit                         0x7fff313ee1a6 -[NSTextField textDidEndEditing:] + 937
23 CommandPost                    0x10692643c -[HSGrowingTextField textDidEndEditing:] (HSGrowingTextField.m:20)
24 CoreFoundation                 0x7fff33c71a3c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
25 CoreFoundation                 0x7fff33c7192a _CFXRegistrationPost + 442
26 CoreFoundation                 0x7fff33c71672 ___CFXNotificationPost_block_invoke + 50
27 CoreFoundation                 0x7fff33c2f450 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1664
28 CoreFoundation                 0x7fff33c2e583 _CFXNotificationPost + 595
29 Foundation                     0x7fff35d213c7 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
30 AppKit                         0x7fff3156277a -[NSTextView(NSPrivate) _giveUpFirstResponder:] + 440
31 AppKit                         0x7fff313db0ff -[NSTextView doCommandBySelector:] + 200
32 AppKit                         0x7fff313db013 -[NSTextInputContext(NSInputContext_WithCompletion) doCommandBySelector:completionHandler:] + 118
33 AppKit                         0x7fff313bc55a -[NSKeyBindingManager(NSKeyBindingManager_MultiClients) interpretEventAsCommand:forClient:] + 2898
34 AppKit                         0x7fff31c55523 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke.1109 + 360
35 AppKit                         0x7fff31c55352 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke_3 + 79
36 AppKit                         0x7fff313c3d95 -[NSTextInputContext tryHandleEvent_HasMarkedText_withDispatchCondition:dispatchWork:continuation:] + 92
37 AppKit                         0x7fff31c552d1 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke.1099 + 251
38 HIToolbox                      0x7fff32fa3b7e __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_5 + 70
39 HIToolbox                      0x7fff32fa2a36 ___ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec_block_invoke + 110
40 AppKit                         0x7fff31c4dd30 __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke.320 + 580
41 AppKit                         0x7fff313bd8eb __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke_2 + 79
42 AppKit                         0x7fff313bd86e -[NSTextInputContext tryHandleTSMEvent_HasMarkedText_withDispatchCondition:dispatchWork:continuation:] + 92
43 AppKit                         0x7fff313bd3d1 -[NSTextInputContext handleTSMEvent:completionHandler:] + 1722
44 AppKit                         0x7fff313bcca1 _NSTSMEventHandler + 311
45 HIToolbox                      0x7fff32f4c814 DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1541
46 HIToolbox                      0x7fff32f4bb5d SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 374
47 HIToolbox                      0x7fff32f4b9d3 SendEventToEventTargetWithOptions + 45
48 HIToolbox                      0x7fff32f9fc89 SendTSMEvent_WithCompletionHandler + 389
49 HIToolbox                      0x7fff32fa0154 __SendUnicodeTextAEToUnicodeDoc_WithCompletionHandler_block_invoke + 403
50 HIToolbox                      0x7fff32f9ffb2 __SendFilterTextEvent_WithCompletionHandler_block_invoke + 219
51 HIToolbox                      0x7fff32f9fcd8 SendTSMEvent_WithCompletionHandler + 468
52 HIToolbox                      0x7fff32f9fad7 SendFilterTextEvent_WithCompletionHandler + 233
53 HIToolbox                      0x7fff32f9f796 SendUnicodeTextAEToUnicodeDoc_WithCompletionHandler + 290
54 HIToolbox                      0x7fff32f9f54a __utDeliverTSMEvent_WithCompletionHandler_block_invoke_2 + 289
55 HIToolbox                      0x7fff32f9f3cb __utDeliverTSMEvent_WithCompletionHandler_block_invoke + 405
56 HIToolbox                      0x7fff32f9f1b8 TSMKeyEvent_WithCompletionHandler + 636
57 HIToolbox                      0x7fff32f9eefc __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_4 + 262
58 HIToolbox                      0x7fff32f9ed17 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_3 + 263
59 HIToolbox                      0x7fff32f9ea52 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_2 + 288
60 HIToolbox                      0x7fff32f9e7a8 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke + 280
61 HIToolbox                      0x7fff32f9dd9f TSMProcessRawKeyEventWithOptionsAndCompletionHandler + 3433
62 AppKit                         0x7fff31c5514d __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke.1090 + 115
63 AppKit                         0x7fff31c5451b __204-[NSTextInputContext tryTSMProcessRawKeyEvent_orSubstitution:dispatchCondition:setupForDispatch:furtherCondition:doubleSpaceSubstitutionCondition:doubleSpaceSubstitutionWork:dispatchTSMWork:continuation:]_block_invoke.1016 + 120
64 AppKit                         0x7fff31c54384 -[NSTextInputContext tryTSMProcessRawKeyEvent_orSubstitution:dispatchCondition:setupForDispatch:furtherCondition:doubleSpaceSubstitutionCondition:doubleSpaceSubstitutionWork:dispatchTSMWork:continuation:] + 255
65 AppKit                         0x7fff31c54b91 -[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:] + 1237
66 AppKit                         0x7fff31c54211 -[NSTextInputContext _handleEvent:allowingSyntheticEvent:] + 114
67 AppKit                         0x7fff313bb74a -[NSView interpretKeyEvents:] + 209
68 AppKit                         0x7fff313bb56e -[NSTextView keyDown:] + 724
69 AppKit                         0x7fff31b73029 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 5040
70 AppKit                         0x7fff31b7185c -[NSWindow(NSEventRouting) sendEvent:] + 497
71 AppKit                         0x7fff319d2fa3 -[NSApplication(NSEvent) sendEvent:] + 2751
72 AppKit                         0x7fff31233d9d -[NSApplication run] + 812
73 AppKit                         0x7fff31202f1a NSApplicationMain + 804
74 libdyld.dylib                  0x7fff5b4b0115 start + 1

#1. Thread
0  libsystem_kernel.dylib         0x7fff5b600562 __workq_kernreturn + 10
1  libsystem_pthread.dylib        0x7fff5b73b26f _pthread_wqthread + 1552
2  libsystem_pthread.dylib        0x7fff5b73ac4d start_wqthread + 13

#2. com.twitter.crashlytics.mac.MachExceptionServer
0  CommandPost                    0x1069e1ea1 CLSProcessRecordAllThreads + 1449
1  CommandPost                    0x1069e1d3e CLSProcessRecordAllThreads + 1094
2  CommandPost                    0x1069d162d CLSHandler + 45
3  CommandPost                    0x1069cc721 CLSMachExceptionServer + 546
4  libsystem_pthread.dylib        0x7fff5b73b6c1 _pthread_body + 340
5  libsystem_pthread.dylib        0x7fff5b73b56d _pthread_start + 375
6  libsystem_pthread.dylib        0x7fff5b73ac5d thread_start + 13

#3. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x7fff5b5f67c2 mach_msg_trap + 10
1  libsystem_kernel.dylib         0x7fff5b5f5cdc mach_msg + 60
2  CoreFoundation                 0x7fff33c5d355 __CFRunLoopServiceMachPort + 341
3  CoreFoundation                 0x7fff33c5c6a7 __CFRunLoopRun + 1783
4  CoreFoundation                 0x7fff33c5bd23 CFRunLoopRunSpecific + 483
5  CFNetwork                      0x7fff32dd4f84 -[__CoreSchedulingSetRunnable runForever] + 722
6  Foundation                     0x7fff35d49e48 __NSThread__start__ + 1197
7  libsystem_pthread.dylib        0x7fff5b73b6c1 _pthread_body + 340
8  libsystem_pthread.dylib        0x7fff5b73b56d _pthread_start + 375
9  libsystem_pthread.dylib        0x7fff5b73ac5d thread_start + 13

#4. Thread
0  libsystem_kernel.dylib         0x7fff5b5ffcee __psynch_cvwait + 10
1  libsystem_pthread.dylib        0x7fff5b73c662 _pthread_cond_wait + 732
2  libc++.1.dylib                 0x7fff594e5cb0 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3  JavaScriptCore                 0x7fff37753ae6 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 86
4  JavaScriptCore                 0x7fff37753a1b bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 139
5  JavaScriptCore                 0x7fff37753d48 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 40
6  libsystem_pthread.dylib        0x7fff5b73b6c1 _pthread_body + 340
7  libsystem_pthread.dylib        0x7fff5b73b56d _pthread_start + 375
8  libsystem_pthread.dylib        0x7fff5b73ac5d thread_start + 13

#5. com.apple.NSEventThread
0  libsystem_kernel.dylib         0x7fff5b5f67c2 mach_msg_trap + 10
1  libsystem_kernel.dylib         0x7fff5b5f5cdc mach_msg + 60
2  CoreFoundation                 0x7fff33c5d355 __CFRunLoopServiceMachPort + 341
3  CoreFoundation                 0x7fff33c5c6a7 __CFRunLoopRun + 1783
4  CoreFoundation                 0x7fff33c5bd23 CFRunLoopRunSpecific + 483
5  AppKit                         0x7fff3137c3c8 _NSEventThread + 184
6  libsystem_pthread.dylib        0x7fff5b73b6c1 _pthread_body + 340
7  libsystem_pthread.dylib        0x7fff5b73b56d _pthread_start + 375
8  libsystem_pthread.dylib        0x7fff5b73ac5d thread_start + 13

#6. Thread
0  libsystem_kernel.dylib         0x7fff5b5f67c2 mach_msg_trap + 10
1  libsystem_kernel.dylib         0x7fff5b5f5cdc mach_msg + 60
2  CoreMIDI                       0x7fff349f1b83 XServerMachPort::ReceiveMessage(int&, void*, int&) + 93
3  CoreMIDI                       0x7fff34a089a0 MIDIProcess::RunMIDIInThread() + 336
4  CoreMIDI                       0x7fff34a19c8e XThread::RunHelper(void*) + 10
5  CoreMIDI                       0x7fff34a1de7b CAPThread::Entry(CAPThread*) + 77
6  libsystem_pthread.dylib        0x7fff5b73b6c1 _pthread_body + 340
7  libsystem_pthread.dylib        0x7fff5b73b56d _pthread_start + 375
8  libsystem_pthread.dylib        0x7fff5b73ac5d thread_start + 13

#7. com.apple.coreanimation.render-server
0  libsystem_kernel.dylib         0x7fff5b5f67c2 mach_msg_trap + 10
1  libsystem_kernel.dylib         0x7fff5b5f5cdc mach_msg + 60
2  QuartzCore                     0x7fff3ed31e4d CA::Render::Server::server_thread(void*) + 481
3  QuartzCore                     0x7fff3ed31c5e thread_fun + 25
4  libsystem_pthread.dylib        0x7fff5b73b6c1 _pthread_body + 340
5  libsystem_pthread.dylib        0x7fff5b73b56d _pthread_start + 375
6  libsystem_pthread.dylib        0x7fff5b73ac5d thread_start + 13

#8. Thread
0  libsystem_kernel.dylib         0x7fff5b600562 __workq_kernreturn + 10
1  libsystem_pthread.dylib        0x7fff5b73b26f _pthread_wqthread + 1552
2  libsystem_pthread.dylib        0x7fff5b73ac4d start_wqthread + 13

#9. Thread
0  libsystem_kernel.dylib         0x7fff5b600562 __workq_kernreturn + 10
1  libsystem_pthread.dylib        0x7fff5b73b06a _pthread_wqthread + 1035
2  libsystem_pthread.dylib        0x7fff5b73ac4d start_wqthread + 13
3  (Missing)                      0x700008615b20 (Missing)

#10. Thread
0  libsystem_kernel.dylib         0x7fff5b600562 __workq_kernreturn + 10
1  libsystem_pthread.dylib        0x7fff5b73b26f _pthread_wqthread + 1552
2  libsystem_pthread.dylib        0x7fff5b73ac4d start_wqthread + 13

```
