### ISSUE TITLE
Breaking issues from 0.9.79

### ISSUE THREAD

**Issue by grchen** [Hammerspoon/hammerspoon#2484]
2020-09-21 16:08:16: *** ERROR: ...n.app/Contents/Resources/extensions/hs/window/filter.lua:1431: attempt to index a nil value (field '_element')
stack traceback:
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1431: in upvalue 'startAppWatcher'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1559: in upvalue 'startGlobalWatcher'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1722: in upvalue 'start'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1913: in method 'subscribe'
	/Users/grchen/iWork/hammerspoon/input/input.lua:16: in local 'set_app_input_method'
	/Users/grchen/iWork/hammerspoon/input/input.lua:21: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:651: in function 'require'
	/Users/grchen/iWork/hammerspoon/init.lua:19: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:702: in function 'hs._coresetup.setup'
	(...tail calls...)

src code:

local function Chinese()
    hs.console.printStyledtext("chinese")
    hs.keycodes.currentSourceID("com.apple.inputmethod.SCIM.ITABC")
  end
  local function English()
    hs.console.printStyledtext(hs.keycodes.currentSourceID())
    hs.keycodes.currentSourceID("com.apple.keylayout.ABC")
  end

  hs.console.printStyledtext("inputM:" .. hs.keycodes.currentSourceID())

  local function set_app_input_method(app_name, set_input_method_function, event)
    event = event or hs.window.filter.windowFocused
    hs.window.filter.new(app_name)
      :subscribe(event, function() set_input_method_function() end)
  end

  set_app_input_method('Hammerspoon', English)
  set_app_input_method('Alfred', English)
  set_app_input_method('iTerm2', English)
  set_app_input_method('Dash', English)

**Comment by cmsj** [comment]
This should be fixed in 0.9.80 which has just been released.

**Comment by zzamboni** [comment]
@cmsj unfortunately with 0.9.80 I'm still seeing errors. Window resizing after Hammerspoon starts works fine, but if I try to move a window to a different screen, I get:
```
2020-09-21 11:09:22: 11:09:22 ERROR:   LuaSkin: hs.hotkey callback: ...mmerspoon/Spoons/WindowScreenLeftAndRight.spoon/init.lua:60: attempt to call a nil value (method 'moveOneScreenEast')
stack traceback:
	...mmerspoon/Spoons/WindowScreenLeftAndRight.spoon/init.lua:60: in function 'WindowScreenLeftAndRight.moveCurrentWindowToScreen'
	(...tail calls...)
```

Furthermore, after this, all window-resizing calls now fail as well.

**Comment by shuiqingliu** [comment]
same issue

**Comment by asmagill** [comment]
Check #2488 and see if that fixes this latest error. It's already in master, but if you don't want to do a full rebuild, you can make the changes directly by editing `/Applications/Hammerspoon.app/Contents/Resources/exxtensions/hs/window/init.lua` -- they're pretty simple changes -- and restarting/reloading Hammerspoon.

**Comment by zzamboni** [comment]
@asmagill thanks! I can confirm that master works well for me. Looking forward to the new release!
