### ISSUE TITLE
Support handoff when set as the default Browser

### ISSUE THREAD

**Issue by ghostflyby** [Hammerspoon/hammerspoon#3499]
Currently the handoff received web pages are opened with Safari, even with hammerspoon set as the default browser.

**Comment by cmsj** [comment]
I believe this should be fixed in 1.0.0 which we released yesterday.

**Comment by ghostflyby** [comment]
The issue persists in 1.0.0 as https://github.com/Hammerspoon/hammerspoon/pull/3635 has not yet been released.
