### ISSUE TITLE
HS waiting to display drawings until all drawings are ready

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#629]
I'm trying to see if HS can replace GeekTool.  In particular, I now have replicated 13 "Geeklets" in HS; 12 of them are text drawings and 1 is an image drawing.  Eleven of these text drawings get the text to display via `hs.execute(somescript)`.

Testing all of this requires, of course, frequent reloading of HS.  This led me to notice the following severely annoying behavior.  If I reload HS (or start fresh after a "quit"), then none of the drawings actually get rendered until ALL of the scripts have completed and returned their stdout to HS.  In the meantime, HS only displays white rectangles in the places where the drawings will eventually get rendered.

Needless to say, in GeekTool, all of their "drawings" (shell geeklets or image geeklets or file geeklets) operate independently.  Upon a refresh in GeekTool, the individual drawings display the text whenever the shell script is done returning it, and they don't wait for any other drawings.

Can this be fixed?  If not, I think I'm going to abandon this idea of replacing GeekTool with HS.  Some of my "geeklets" check for the presence of new email messages on IMAP servers, so the "freezeup" can easily take 20 seconds or more, depending on network congestion.  Eventually, I was going to replicate other Geeklets that fetch weather maps from remote sources; this will also cause things to stall.

**Comment by asmagill** [comment]
Hammerspoon's Lua is single threaded so the simple answer is no, any blocking behavior is going to cause Hammerspoon/Lua to wait.  HTTP requests can be done asynchronously, which means they can trigger a callback when completed, but at present there is no way I know of to do this for scripts. You can kind of fake it with staggered timers, if your delays are pretty predictable and relatively short, but that's hacky and doesn't degenerate or scale well.

At one point I was looking into creating a module for NSTask, which should allow running scripts in the background and triggering a callback when completed.  Perhaps this should be looked into again.

**Comment by chdiza** [comment]
> Hammerspoon's Lua is single threaded so the simple answer is no

Ah, that's too bad.  If those callbacks ever get implemented, I'll try again.

**Comment by cmsj** [comment]
fwiw, I decouple the gathering of data from the drawings. I have things write little data files which my HS config can read to get status.

Having said that, I would not be against the idea of asyncronous task execution, so long as we have enough API to ensure that tasks which are getting stuck (e.g. things taking a very long time to complete because network or IO issues) can be cancelled, to avoid spamming the user's system with tons of timers spawning things.

**Comment by chdiza** [comment]
> fwiw, I decouple the gathering of data from the drawings. I have things write little data files which my HS config can read to get status.

I presume you mean that you have non-HS processes write to the little data files.  I thought of this, but the reason I've been using GeekTool's shell geeklets (rather than file geeklets) for years now is that I didn't want to have to create cron jobs or something else like that to run the scripts that gather the data at the relevant intervals.

> so long as we have enough API to ensure that tasks which are getting stuck

Amen.  GeekTool occasionally barfs on things like this.

**Comment by cmsj** [comment]
Yeah, it's definitely nicer when the tasks are encapsulated in the tool visualising their output.

I will spend some time today making an hs.task module that wraps NSTask. I think an important part of this will be encouraging usage patterns that prevent the user from accidentally DoSing themselves, since it's probably quite likely that hs.task would be launched via hs.timer events.

**Comment by lowne** [comment]
If the problem is the rendering (as opposed to HS blocking in general) this is more about drawing implementation than async stuff; specifically, they should probably start out as transparent rects (as opposed to white) upon construction, before all the :setXXXX calls.

@chdiza if your config is available somewhere, I can see if I can spot possible improvements; at any rate, some considerations:
1. if you aren't already, reuse your drawings (via `:setText()` and `:setFrame()`) - at least you'll avoid the white rectangle problem
2. having the "geeklets" on separate callbacks should also help (but the seldom-running, 20s blocking mail check would still freeze the other geeklets)
3. to build on @cmsj suggestion, instead of using cron you can do something like `o,s,t,r=hs.execute('ping -c 5 google.com > data.txt &'); hs.timer.new(10,drawResult)`; adjust the 10s delay to whatever is appropriate and have your drawing read from `data.txt` (seems to work here with multiple background jobs even without passing `true` for `with_user_env`)

@cmsj unless I'm spouting nonsense (I don't trust myself around shells) perhaps the pattern above (#3) could be "promoted" to `hs.execute(cmd,env,callback)`? Where if callback is provided, the job is magically wrapped by having it `touch` a tempfile semaphore when done and then backgrounded, and a transient pathwatcher on the semaphore is set up to call `callback` with the captured stdout when finished. But there must be many caveats (e.g. possibly dealing with different user shells)...

**Comment by chdiza** [comment]
A couple of further points...

First, I forgot to stress that at least some of the "lag" is really down to rendering, and not a trivial portion.  For instance, even the sample init from the other thread, where there's only one shell-out and it's just to "ls" displays the startup and refresh lag.  I get white rectangles where the "geeklet" and a separtate `hs.alert` are to appear.  It's much briefer than when I have lots of "geeklets" up, but it's still there and noticeable.

Second, it really seemed to me (based on subjective time-taken measures) that HS was not running the scripts in series, but rather in parallel; the lag was not the sum of the script-execution times, but was rather equal to the longest of the individual script-execution times.  Or so it seemed.  Obviously I defer to you guys here, since you know what HS could even possibly be doing and I don't.

**Comment by chdiza** [comment]
> if you aren't already, reuse your drawings (via :setText() and :setFrame()) - at least you'll avoid the white rectangle problem

I am using setText(), but not setFrame().  The former is not sufficient to eliminate the white rectangle problem; it doesn't touch it at all.  I can try the latter, but I don't see what the advantage would be.  I am reusing my drawing objects.  They are set down once, and periodically setText() refreshes with new script-output.

I'll work on cleaning up the init file enough to gist it.

> having the "geeklets" on separate callbacks should also help

I don't know what "separate callbacks" means.

The little tempfiles idea is a no-go for me.  It makes it not worth it to use HS over GeekTool.

**Comment by cmsj** [comment]
I've just pushed a quick implementation of hs.task. Anyone who is interested, please take a look at it and let me know if it helps :)

**Comment by chdiza** [comment]
@cmsj I'm eager to play with this.  But just so I don't waste hours being an idiot with trial and error, is the following a correct example of how I would get the output of `ls -l`?
```lua
my_ls_runner = hs.task.new("/bin/ls -l", show_the_results(exitcode, stdout, stderr))

function show_the_results(exitcode, stdout, stderr)
  if not ( exitcode  = 0 )
    some_already_existing_geeklet:setText(stdout)
  else
    some_already_existing_geeklet:setText(stderr)
  end
end

my_ls_runner:start()
```

Or perhaps the path to the executable should be pointing at a lua file that updates my geeklets by using hs.execute?  (I'm unclear as to whether I should be replacing `hs.execute` with `hs.task`, or whether I can/should be using `hs.execute` inside an `hs.task`.)

Also, when you say that an hs.task object can only be used once, does this mean I don't have to manually delete them after they've served their purpose?  In the inline docs I see no `delete` or `destroy` methods.

**Comment by chdiza** [comment]
OK, I think I get the basics, but I still have the two questions mentioned after the above sample script.

**Comment by cmsj** [comment]
@chdiza `hs.task.new("/bin/ls", show the results, {"-l"})`. This is a direct replacement for hs.execute that allows the commands to run in the background and return their result/output to a callback. It doesn't mix with hs.execute and you can't point it at a lua file.

There's no need to manually delete them, just dereference them and garbage collection will take care of it. I haven't converted my geeklets from hs.execute to hs.task yet, but my guess is I'll have an hs.timer object that creates the hs.task objects, but only if the callback has run and marked a variable as "this task completed". I suspect it would be useful to have some API on hs.task for "is this running or not?", for precisely that case

**Comment by chdiza** [comment]
> just dereference them 

Forgive my lua-ignorance, but I don't know what it means to "dereference" them.  Does it mean "to stop having a variable that refers to the hs.task object"?  If that's what it means should I be doing `myobject=""` (or similar), or does it suffice to give the variable `myobject` a brand new hs.task object when the timer says "time to refresh the geeklet?"

**Comment by chdiza** [comment]
@cmsj I was able to get a single geeklet up and running as a test case last night before bedtime.  So far, all seems to be well.  I had a geeklet display "hello" upon creation of the hs.drawing.text object, and then replace it with whatever script output `hs.task` returned.  No white rectangle, no OS X beach ball, no reverse-video menubar icon.  I'm excited about this!

I'll convert the rest, and then I can monitor the memory usage and so forth.

> my guess is I'll have an hs.timer object that creates the hs.task objects, but only if the callback has run and marked a variable as "this task completed"

This is basically what I did.

**Comment by chdiza** [comment]
OK, I've converted all of the geeklets I had before.  It seems to work OK, but I'm getting some intermittent crashing.  Sometimes it happens around five minutes or so after HS opens up.  None of my geeklets are on a 5-min timer, though.

The console shows this:
```
11/07/15 2:37:14.852 p com.apple.xpc.launchd[1]: (org.hammerspoon.Hammerspoon.105952[18095]) Service exited due to signal: Segmentation fault: 11
```
And there's a crash report which I've put in [this gist](https://gist.github.com/6c00963d8deddf6d0c5a).

**Comment by chdiza** [comment]
I don't know if the following Console messages are bad, or whether they're related to the crash, but they looked worth reporting:
```
Nov  7 15:56:17 diza Hammerspoon[44192]: Unknown class 'SUUpdater', using 'NSObject' instead. Encountered in Interface Builder file at path /Applications/.storage/Hammerspoon.app/Contents/Resources/MainMenu.nib.
Nov  7 15:56:17 diza Hammerspoon[44192]: Could not connect action, target class NSObject does not respond to -checkForUpdates:
Nov  7 15:56:17 diza Hammerspoon[44192]: createLuaState
Nov  7 15:56:18 diza WindowServer[21217]: disable_update_timeout: UI updates were forcibly disabled by application "Hammerspoon" for over 1.00 seconds. Server has re-enabled them.
Nov  7 15:56:18 diza Hammerspoon[44192]: SecTaskLoadEntitlements failed error=22
Nov  7 15:56:18 diza WindowServer[21217]: common_reenable_update: UI updates were finally reenabled by application "Hammerspoon" after 1.11 seconds [0.90fps] (server forcibly re-enabled them after 1.00 seconds [1.00fps])
```

**Comment by chdiza** [comment]
The HS console tells me 
```
hs.task callback failed
hs.task callback failed
hs.task callback failed
```

I don't know what to do with this information.

**Comment by chdiza** [comment]
The "callback failed" has gone away, but the crashes keep coming.

**Comment by chdiza** [comment]
I intermittently see in the HS console: 
```
Unable to find userdata object for NSTask object. Please file a bug
stack traceback:
-- Loading extension: styledtext
```

**Comment by chdiza** [comment]
hs.task is still causing crashes for me.  I've gisted a distilled `init.lua` [here](https://gist.github.com/958a85ccd2777972ee23).

It's possible that I'm being an idiot lua-wise, but even with just a single "geeklet" using hs.task with a super-simple script (`/bin/ls`) a crash always occurs eventually.  It does seem to take longer to appear with just one geeklet active rather than many, but it always appears.

**Comment by chdiza** [comment]
The latest tweak to hs.task seems to have fixed the crashing.  Thanks!!
