### ISSUE TITLE
styledtext:setString() confusion

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#652]
When reading the docs for hs.styledtext:setString(), I'm under the impression that it should behave as follows.  I have a styledtext object `foo`, the string of which is "onetwothree".  If I do:
`foo:setString("two")` then I should get back a styledtext object whose string is "two".  In fact, I get one whose string is "twotwothree".

Am I misunderstanding the docs?  If so, how can I get the expected behavior?

**Comment by asmagill** [comment]
Show me the code... I have an idea as to the cause, but I want to see your exact example so I can be certain.

**Comment by chdiza** [comment]
In the HS console:
```lua
foo = hs.styledtext.ansi("onetwothree", {})
foo = foo.setString("two")
foo
```

Also, FYI, if instead of "two" as the new text, I pick the empty string "", the HS crashes immediately.

**Comment by chdiza** [comment]
Also, the styledtext doesn't have to be an "ansi" one; even hs.styledtext.new will do it.

**Comment by asmagill** [comment]
Hmm... my thought was wrong... Not sure why its not working... and the ""... thought I took care of all of those.  Ok, I'll look at it and will get a fix pushed later today.

**Comment by asmagill** [comment]
That should do it... stupid mistake... I was checking the substring sizes, not the destination sizes, for replacement range

**Comment by chdiza** [comment]
Thanks!  One problem still remains.  If the styledtext object was of the "ansi" variety, and the new string given to setString() has ANSI escape sequences, then the resulting styledtext object doesn't interpret the escape sequences and outputs the ANSI sequences literally.

**Comment by asmagill** [comment]
ANSI isn't a state for the string, it's a conversion of certain sequences into NSAttributedString attributes.  If the new string also contains ANSI escape sequences, you need to do something like `foo = foo:setString(hs.styledtext.ansi(newString, { defaultAttributes }))`
