### ISSUE TITLE
hs command line tool

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#827]
Sometime between the last release and the current development build, using the `hs` command line tool errors with the following on my machine:

~~~sh
$ hs
Hammerspoon interactive prompt.

dyld: lazy symbol binding failed: Symbol not found: _readline
  Referenced from: /opt/amagill/bin/hs
  Expected in: flat namespace

dyld: Symbol not found: _readline
  Referenced from: /opt/amagill/bin/hs
  Expected in: flat namespace

Trace/BPT trap: 5
~~~

On another machine I sometimes have access to, the error is:

~~~sh
$ hs 
dyld: Library not loaded: @rpath/libclang_rt.asan_osx_dynamic.dylib
  Referenced from: /Users/amagill/Applications/./Hammerspoon.app/Contents/Resources/extensions/hs/ipc/bin/hs
  Reason: image not found
Trace/BPT trap: 5
~~~

I'll try and take a closer look at it in the next couple of days, unless someone else has an idea before then.

**Comment by heptal** [comment]
Found it and fixed in #828. For whatever reason either libedit or libreadline needs to be explicitly linked with the `hs` target in Build Phases. I already had an idea because I removed all the explicit framework linking in a previous commit to let Xcode module resolution do the job.

**Comment by cmsj** [comment]
good catch, good fix, thanks very much folks :)

**Comment by mvgrimes** [comment]
This issue is back in 0.9.86. `hs` works find in version 0.9.85.

**Comment by cmsj** [comment]
Can you post the output from a terminal of: `ls -l $(which hs)`

**Comment by mvgrimes** [comment]
```
─ ls -l $( which hs )
lrwxr-xr-x  1 mgrimes  admin  73 Mar 15 11:11 /usr/local/bin/hs@ -> /Applications/Hammerspoon.app/Contents/Resources/extensions/hs/ipc/bin/hs

╰─ otool -L $(which hs)
/usr/local/bin/hs:
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1770.255.0)
        /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1770.255.0)
        /usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
        @rpath/libclang_rt.asan_osx_dynamic.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
        /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version
2022.20.117)
```

**Comment by cmsj** [comment]
Thanks. Is it the libclang_rt.asan library it's complaining about?

**Comment by mvgrimes** [comment]
Yes:

```
╰─ hs
dyld: Library not loaded: @rpath/libclang_rt.asan_osx_dynamic.dylib
  Referenced from: /usr/local/bin/hs
  Reason: image not found
```

**Comment by cmsj** [comment]
Ok, that's unfortunate, but the good news is that it's temporary - I'm trying to shake out some particularly strange crash reports we've been getting for a while now, and the current release (0.9.86) has lots of compiler driven memory diagnostic stuff enabled. They will all be disabled again in 0.9.87, so for now I would suggest downgrading to 0.9.85, which you can get from https://github.com/Hammerspoon/hammerspoon/releases/tag/0.9.85 and then wait for 0.9.87 before upgrading again.

Apologies for the disruption!

**Comment by mvgrimes** [comment]
Thanks for the quick response! Hope reporting the issue helps.
