### ISSUE TITLE
Crash when emitting key event

### ISSUE THREAD

**Issue by mwean** [Hammerspoon/hammerspoon#944]
I'm trying to emit a keyboard shortcut to a specific app:

```lua
tomatoes = hs.appfinder.appFromName("Tomatoes")
cmd_n = hs.eventtap.event.newKeyEvent({"cmd"}, "N")
cmd_n:post(tomatoes)
```

I've tried both in config and the console, and I get this crash:

```
Process:               Hammerspoon [54591]
Path:                  /Users/USER/Library/Developer/Xcode/DerivedData/Hammerspoon-ddgdlhvdoklcfzapesaeykcbmsnx/Build/Products/Debug/Hammerspoon.app/Contents/MacOS/Hammerspoon
Identifier:            org.hammerspoon.Hammerspoon
Version:               0.9.46 (0.9.46)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Hammerspoon [54591]
User ID:               501

Date/Time:             2016-07-23 15:39:34.096 -0700
OS Version:            Mac OS X 10.11.5 (15F34)
Report Version:        11
Anonymous UUID:        60EC2E78-E514-8288-5EBA-A0D1A77FF636

Sleep/Wake UUID:       803E18A3-310D-4700-BE49-A99C0C79C17B

Time Awake Since Boot: 290000 seconds
Time Since Wake:       8400 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000500e476
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x500e476:
--> 
    __TEXT                 0000000101be5000-0000000101d3d000 [ 1376K] r-x/rwx SM=COW  /Users/USER/Library/Developer/Xcode/DerivedData/Hammerspoon-ddgdlhvdoklcfzapesaeykcbmsnx/Build/Products/Debug/Hammerspoon.app/Contents/MacOS/Hammerspoon

Application Specific Information:
objc_msgSend() selector name: _cfTypeID


Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff869f54e9 objc_msgSend + 41
1   com.apple.HIServices          	0x00007fff8a86f76d _AXUIElementGetPid + 66
2   event.so                      	0x00000001051b3786 eventtap_event_post + 102 (event.m:229)
3   org.hammerspoon.LuaSkin       	0x0000000101e5cac2 luaD_precall + 418 (ldo.c:360)
4   org.hammerspoon.LuaSkin       	0x0000000101e54dd7 luaV_execute + 14007 (lvm.c:1115)
5   org.hammerspoon.LuaSkin       	0x0000000101e5d3b3 luaD_call + 99 (ldo.c:492)
6   org.hammerspoon.LuaSkin       	0x0000000101e5d479 luaD_callnoyield + 57 (ldo.c:502)
7   org.hammerspoon.LuaSkin       	0x0000000101e5b32f f_call + 47 (lapi.c:943)
8   org.hammerspoon.LuaSkin       	0x0000000101e5c26e luaD_rawrunprotected + 110 (ldo.c:145)
9   org.hammerspoon.LuaSkin       	0x0000000101e5daf5 luaD_pcall + 117 (ldo.c:722)
10  org.hammerspoon.LuaSkin       	0x0000000101e5b1e1 lua_pcallk + 209 (lapi.c:968)
11  org.hammerspoon.LuaSkin       	0x0000000101e40392 -[LuaSkin protectedCallAndTraceback:nresults:] + 290 (Skin.m:199)
12  internal.so                   	0x00000001078e506b trigger_hotkey_callback + 459 (internal.m:310)
13  internal.so                   	0x00000001078e54c9 hotkey_callback + 297 (internal.m:278)
14  com.apple.HIToolbox           	0x00007fff96b197be DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1231
15  com.apple.HIToolbox           	0x00007fff96b18c48 SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 404
16  com.apple.HIToolbox           	0x00007fff96b2e9e6 SendEventToEventTarget + 40
17  com.apple.AppKit              	0x00007fff8855d8ce -[NSApplication sendEvent:] + 2178
18  com.apple.AppKit              	0x00007fff883c4df2 -[NSApplication run] + 796
19  com.apple.AppKit              	0x00007fff8838e368 NSApplicationMain + 1176
20  org.hammerspoon.Hammerspoon   	0x0000000101be89c2 main + 34 (MJAppDelegate.m:206)
21  libdyld.dylib                 	0x00007fff8e1885ad start + 1
```

**Comment by asmagill** [comment]
Fixed in master, if you want to build it yourself, and it will be in the next release in any case.

In addition, you may need to add `true` as the third argument to `newKeyEvent`, since you probably want a key-down event, not a key-up one.

**Comment by mwean** [comment]
That fixed the error, thanks! It's still not working for me though... This is what I have:

```lua
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "N", function()
  tomatoes:activate()
  cmd_n = hs.eventtap.event.newKeyEvent({"cmd"}, "N", true)
  cmd_n:post(tomatoes)
end)
```

It activates the app, but the keyboard shortcut (cmd-n) doesn't have any effect. I tried to do the same thing using KeyboardMaestro and it worked:

![image](https://cloud.githubusercontent.com/assets/732173/17087128/93d853ae-51b7-11e6-8437-13047a279b63.png)

Is there any other way to simulate a keyboard shortcut?

**Comment by cmsj** [comment]
Emitting events can be... interesting :)

Here are some thoughts:

1. I'd suggest you have your function in the `releasedfn` part of the hotkey, otherwise you're still holding down a bunch of keys when we're emitting your eventtap event.
1. You're going to need a second `newKeyEvent()` with the third argument as `false` (you can't really just send a key-down event without a key-up event)
1. I'd put a ~200ms sleep between the eventtap postings, at least, and maybe after the `:activate()` because it might take a moment to execute.

**Comment by asmagill** [comment]
@cmsj's points are probably important enough to merit their own mention in the `hs.eventtap` documentation for `newKeyEvent` -- I've run into this many times before when moving perfectly working code into a hotkey.  As long as you're not holding down the hotkey, the difference is all but imperceptible in terms of responsiveness.

I have found that 10.11 is somewhat forgiving, sometimes, about the later 2 points... except when it's not!  I have reason to suspect 10.12 might not be as forgiving, but I just finished downloading the beta today... hopefully I can start testing later this week.

At any rate, we should probably add an event writeup to the wiki at some point that covers these kinds of things.

And, I can confirm that the following works from the Console as expected (even without the key-up), but I haven't embedded it in a hot-key yet or tested it in many situations:

~~~lua
cmd_n = hs.eventtap.event.newKeyEvent({"cmd"}, "n", true)
cmd_n:post(hs.application("Terminal"))
~~~

**Comment by mwean** [comment]
It seems like third party apps don't behave as well. I tried this and it didn't work. I also tried with iTerm.

```lua
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "N", nil, function()
  tomatoes:activate()

  hs.timer.doAfter(0.2, function()
    hs.eventtap.event.newKeyEvent({"cmd"}, "N", true):post(tomatoes)

    hs.timer.doAfter(0.2, function()
      hs.eventtap.event.newKeyEvent({"cmd"}, "N", false):post(tomatoes)
    end)
  end)
end)
```
